import { mysqlRequest } from './mysqlApi';
const normalize = (s) => ({ ...s, firstName: s.firstName ?? s.first_name, lastName: s.lastName ?? s.last_name, documentId: s.documentId ?? s.document_id, courseId: s.courseId ?? s.course_id });
export const createStudent = (data) => mysqlRequest('/api/estudiantes', { method: 'POST', body: data }).then(normalize);
export const getAllStudents = () => mysqlRequest('/api/estudiantes').then((r) => r.map(normalize));
export const getStudentById = (id) => mysqlRequest(`/api/estudiantes/${id}`).then(normalize);
export const getStudentByEmail = (email) => mysqlRequest(`/api/estudiantes/email/${encodeURIComponent(email)}`).then((r) => r ? normalize(r) : null);
export const getStudentByDocument = (id) => mysqlRequest(`/api/estudiantes/document/${id}`).then((r) => r ? normalize(r) : null);
export const getStudentsByCourse = (id) => mysqlRequest(`/api/estudiantes?courseId=${id}`).then((r) => r.map(normalize));
export const updateStudent = (id, data) => mysqlRequest(`/api/estudiantes/${id}`, { method: 'PUT', body: data }).then(normalize);
export const deleteStudent = (id) => mysqlRequest(`/api/estudiantes/${id}`, { method: 'DELETE' });
export const onStudentsChange = (callback) => { getAllStudents().then(callback); return () => {}; };
