import { mysqlRequest } from './mysqlApi';
export const createSubject = (data) => mysqlRequest('/api/materias', { method: 'POST', body: data });
export const getAllSubjects = () => mysqlRequest('/api/materias');
export const getSubjectById = (id) => mysqlRequest(`/api/materias/${id}`);
export const getSubjectsByCourse = (id) => mysqlRequest(`/api/materias?courseId=${id}`);
export const getSubjectsByTeacher = (options) => mysqlRequest(`/api/materias?teacherId=${typeof options === 'string' ? options : options?.teacherId}`);
export const getSubjectByCriteria = async (criteria) => (await getAllSubjects()).find((row) => Object.entries(criteria).every(([key, value]) => row[key] === value)) || null;
export const updateSubject = (id, data) => mysqlRequest(`/api/materias/${id}`, { method: 'PUT', body: data });
export const deleteSubject = (id) => mysqlRequest(`/api/materias/${id}`, { method: 'DELETE' });
export const onSubjectsChange = (callback) => { getAllSubjects().then(callback); return () => {}; };
export const onSubjectsCourseChange = (id, callback) => { getSubjectsByCourse(id).then(callback); return () => {}; };
