import { mysqlRequest } from './mysqlApi';
const normalize = (t) => ({ ...t, firstName: t.firstName ?? t.first_name, lastName: t.lastName ?? t.last_name, documentId: t.documentId ?? t.document_id });
export const createTeacher = (data) => mysqlRequest('/api/docentes', { method: 'POST', body: data }).then(normalize);
export const getAllTeachers = () => mysqlRequest('/api/docentes').then((r) => r.map(normalize));
export const getTeacherById = (id) => mysqlRequest(`/api/docentes/${id}`).then(normalize);
export const getTeacherByDocument = (id) => mysqlRequest(`/api/docentes/document/${id}`).then((r) => r ? normalize(r) : null);
export const updateTeacher = (id, data) => mysqlRequest(`/api/docentes/${id}`, { method: 'PUT', body: data }).then(normalize);
export const deleteTeacher = (id) => mysqlRequest(`/api/docentes/${id}`, { method: 'DELETE' });
export const teacherService = { createTeacher, getAllTeachers, getTeacherById, getTeacherByDocument, updateTeacher, deleteTeacher };
export default teacherService;
